name: 喜马拉雅极速定制版

on:
    workflow_dispatch:
    schedule:
        - cron: "3,15,20 * * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 当当找新书"
              run: python3 xmly_speed.py
              env:
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
