name: 中青看点阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '6 1-10/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ2 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ3 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ4 }}
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ
        run: |
          node onlyOneExecute.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          SYNCURL: https://raw.githubusercontent.com/Sunert/Scripts/master/Task/Youth_Read.js

      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ2
        run: |
          node onlyOneExecute.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2 }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          SYNCURL: https://raw.githubusercontent.com/Sunert/Scripts/master/Task/Youth_Read.js
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ3
        run: |
          node onlyOneExecute.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3 }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          SYNCURL: https://raw.githubusercontent.com/Sunert/Scripts/master/Task/Youth_Read.js
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ4
        run: |
          node onlyOneExecute.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4 }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          SYNCURL: https://raw.githubusercontent.com/Sunert/Scripts/master/Task/Youth_Read.js
