name: 中青看点视频

on:
  workflow_dispatch:
  schedule:
     - cron: '10 1-4 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: |
          npm install
                
      - name: '运行 【中青看点-视频观看-51】'
        run: |
          node onlyOneExecute.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_VIDEO }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          SYNCURL: https://raw.githubusercontent.com/Sunert/Scripts/master/Task/Youth_Read.js

      - name: '运行 【中青看点-视频观看2-50】'
        run: |
          node onlyOneExecute.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_VIDEO2 }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          SYNCURL: https://raw.githubusercontent.com/Sunert/Scripts/master/Task/Youth_Read.js
